In [1]:
import torch
from opt_src import config_parser
from data import dataset_dict
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
img_idx = torch.load('configs/pairs.th')[f'dtu_train']

In [3]:
img_idx[:3]

[25, 21, 33]

In [4]:
test_idx = torch.load('configs/pairs.th')[f'dtu_test']

In [5]:
test_idx

[32, 24, 23, 44]

In [6]:
# dataset = dataset_dict['dtu_ft']

# scene = 1

# cmd = f'--datadir /mnt/hdd/mvsnerf_data/dtu/scan{scene}  \
#      --dataset_name dtu_ft  \
#      --net_type v0 --ckpt ./ckpts/mvsnerf-v0.tar '

# args = config_parser(cmd.split())

# dataset_train = dataset(args, split='train')

==> image down scale: 1.0
===> training index: [25, 21, 33, 22, 14, 15, 26, 30, 31, 35, 34, 43, 46, 29, 16, 36]


/home/youngsun/.local/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [7]:
# load dtu_src not dtu_ft

dataset = dataset_dict['dtu_src']

scene = 1

cmd = f'--datadir /mnt/hdd/mvsnerf_data/dtu/  \
     --dataset_name dtu_src  \
     --net_type v0 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 6 --num_src_views 3 --views_type dense'

args = config_parser(cmd.split())

dataset_train = dataset(root_dir='/mnt/hdd/mvsnerf_data/dtu/', split='train', views_type='dense', n_views=3, max_len=10, downSample=1.0)

==> image down scale: 1.0


/home/youngsun/.local/lib/python3.8/site-packages/numpy/core/shape_base.py:420: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrays = [asanyarray(arr) for arr in arrays]


# Plot camera positions 

## All cameras

In [10]:
fig = go.Figure(data=[go.Scatter3d(x=dataset_train.cam2worlds[:,0,3], 
                                   y=dataset_train.cam2worlds[:,1,3], 
                                   z=-dataset_train.cam2worlds[:,2,3],
                                   mode='lines+markers',
                                   marker=dict(
                                        size=4,
                                        color=np.arange(49),                # set color to an array/list of desired values
                                        colorscale='Viridis',   # choose a colorscale
                                        opacity=0.8, showscale=True
                                    ),
                                   line=dict(
                                        color='darkblue',
                                        width=2
                                   )
                                  
                                  )])
fig.show()

# Write dtu_all_pairs.txt

In [44]:
with open('./configs/dtu_all_pairs.txt', 'w') as f:
    
    f.write('49\n')
    
    for num, camera in enumerate(cameras):
        
        f.write(f'{num}\n48 ')

        # find nearest image idx
        dis = np.sum(np.abs(cameras - camera), axis=-1)
        pair_dis = np.sort(dis)[1:]
        pair_idx = np.argsort(dis)[1:]

        for idx, dist in zip(pair_idx, pair_dis):
            f.write(f'{idx} {dist:.3f} ')
        f.write('\n')

In [45]:
np.rint(0.3)

0.0

In [46]:
torch.randperm(48)

tensor([34, 13, 24, 38, 36, 10, 46, 11, 17, 12, 25, 40, 20,  3, 14,  2, 22, 30,
        44, 48, 26, 31,  5,  9, 21, 27,  0,  1, 37, 42, 41, 18,  7, 32, 29,  8,
         6, 43, 16, 19, 28, 39,  4, 33, 45, 23, 15, 47, 35])

In [55]:
0 48
0 24 48
0 16 32 48

SyntaxError: invalid syntax (3106548219.py, line 1)

In [77]:
n=13
np.arange(0,48,48//n - 1)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [82]:
torch.linspace(0, 47, steps=4)

tensor([ 0.0000, 15.6667, 31.3333, 47.0000])

In [106]:
test = 6 * (torch.rand_like(torch.linspace(0, 47, steps=4)) - 0.5)

In [107]:
test

tensor([1.9868, 1.8895, 0.2050, 0.2646])

In [112]:
test.round()

tensor([2., 2., 0., 0.])

In [3]:
torch.randperm(48)

tensor([39,  7, 38, 18, 14, 31, 47, 21, 42,  5, 17, 23, 20, 26, 29, 19, 30,  9,
         1, 34, 28, 44,  8, 37, 43, 40, 36,  2, 22,  4, 16,  6, 10, 25,  3, 41,
        27, 32, 45, 13, 46, 12, 15, 11, 33,  0, 24, 35])

In [32]:
 np.random.choice(range(23,25))

ValueError: Cannot take a larger sample than population when 'replace=False'

In [43]:
torch.linspace(0, 47, steps=9)

tensor([ 0.0000,  5.8750, 11.7500, 17.6250, 23.5000, 29.3750, 35.2500, 41.1250,
        47.0000])

In [60]:
ids = torch.linspace(0, 47, steps=2).round()

In [64]:
[np.random.choice(range(int(ids[i]), int(ids[i+1]))) for i in range(len(ids)-1)]

[18, 38]

In [63]:
for i in range(len(ids)-1): print(i)

0
1


In [65]:
torch.linspace(0, 47, steps=2).round()

tensor([ 0., 47.])